name: C/C++ CI
on:
  push:
    tags:
      - v*   

jobs:
  build_and_release_on_windows:
    runs-on: windows-latest
    env:
      artifactName: P4GPC_Savegame_Helper
      CC: cl
      CXX: cl 
    steps:
      - uses: actions/checkout@v2

      - uses: ilammy/msvc-dev-cmd@v1
        with:
            arch: x86
        #   toolset: 14.16

      - name: build with cmake
        uses: lukka/run-cmake@v2
        with:
            cmakeListsOrSettingsJson: CMakeSettingsJson
            configurationRegexFilter: 'Release'
            buildDirectory: ${{ runner.temp }}/build

      - name: pack
        id: pack
        run: |
          Get-ChildItem -Recurse -Path .
          $FULL_NAME="${{env.artifactName}}_${{runner.os}}"
          cmake --install ./build/x86-Release -v --prefix ./$FULL_NAME
          7z a $FULL_NAME ./$FULL_NAME
          echo "::set-output name=full_name::$FULL_NAME"
        working-directory: ${{runner.temp}}
      
      - uses: actions/upload-artifact@v2
        with:
          path: ${{runner.temp}}\${{env.artifactName}}_${{runner.os}}.7z
      
      - uses: marvinpinto/action-automatic-releases@latest
        if: github.event_name == 'push'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            ${{runner.temp}}\${{env.artifactName}}_${{runner.os}}.7z
