name: C/C++ CI
on:
  push:
    tags:
      - v*
  repository_dispatch:
    types: [run_tests]
    
jobs:
  build_and_release_on_windows:
    strategy:
      matrix:
        os: [windows-latest]
        configuration: [Release]

      fail-fast: true
    runs-on: ${{ matrix.os }}
    env:
      artifactName: P4GPC_Savegame_Helper
    steps:
      - uses: actions/checkout@v2

      - uses: ilammy/msvc-dev-cmd@v1
        with:
            arch: x86
        #   toolset: 14.16

      - uses: lukka/run-cmake@v0
        with:
            cmakeListsOrSettingsJson: CMakeSettingsJson
            cmakeSettingsJsonPath: '${{ github.workspace }}/CMakeSettings.json'
            configurationRegexFilter: '${{ matrix.configuration }}'

      #- uses: marvinpinto/action-automatic-releases@latest
      #  with:
      #    repo_token: ${{ github.token }}
      #    prerelease: false
      #    files: |
      #      ${{runner.temp}}\${{env.artifactName}}_${{runner.os}}.7z
